language: bash

services:
  - docker

before_install:
  - docker build -t dockerniklas/spooks .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
